import Header from "../components/Header";
import Calculator from "../components/Calculator";
import ContactForm from "../components/ContactForm";
import {projects,services,site} from "./content";
const Arrow=()=> <span aria-hidden>↗</span>;
export default function Home(){return <><Header/><main id="top">
<section className="hero"><div className="heroGrid"><div><span className="eyebrow">Engineering practice · Lebanon</span><h1>Structures designed with <em>clarity.</em></h1><p>{site.intro}</p><div className="actions"><a className="button" href="#contact">Start a project <Arrow/></a><a className="textLink" href="#portfolio">Explore our work <Arrow/></a></div></div><div className="heroVisual"><div className="gridLines"/><div className="beam b1"/><div className="beam b2"/><div className="beam b3"/><span>RC / STEEL / QS</span></div></div><div className="trust"><span>STRUCTURAL DESIGN</span><span>QUANTITY SURVEYING</span><span>INDUSTRIAL FACILITIES</span><span>TECHNICAL REVIEW</span></div></section>
<section id="services" className="section"><div className="sectionHead"><span className="eyebrow">01 · Services</span><h2>Engineering scope,<br/>from concept to delivery.</h2><p>Focused technical services with clear documentation, practical coordination and attention to constructability.</p></div><div className="cards">{services.map((s,i)=><article className="card" key={s.title}><span className="number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
<section id="portfolio" className="section dark"><div className="sectionHead"><span className="eyebrow">02 · Portfolio</span><h2>Experience across<br/>building typologies.</h2><p>Selected capability areas. Replace these cards with approved project photography and project-specific details.</p></div><div className="projects">{projects.map((p,i)=><article className={`project p${i+1}`} key={p.title}><div className="projectArt"><span>{String(i+1).padStart(2,"0")}</span></div><div><small>{p.category}</small><h3>{p.title}</h3><p>{p.text}</p></div></article>)}</div></section>
<section id="tools" className="section tools"><div className="sectionHead"><span className="eyebrow">03 · Digital engineering</span><h2>Professional tools,<br/>built into the platform.</h2><p>The site is ready to grow into private, server-side calculation workflows, PDF reports and authenticated client access.</p></div><Calculator/></section>
<section id="about" className="section about"><div><span className="eyebrow">04 · About</span><h2>Technical thinking.<br/>Practical outcomes.</h2></div><div className="aboutCopy"><p className="lead">Karam Engineering provides structural engineering and quantity surveying services for industrial, commercial and residential developments.</p><p>The practice combines structural analysis, detailed documentation, quantity measurement and project coordination to support efficient, buildable solutions.</p><div className="stats"><div><strong>RC</strong><span>Reinforced concrete</span></div><div><strong>ST</strong><span>Structural steel</span></div><div><strong>QS</strong><span>Quantity surveying</span></div></div></div></section>
<section id="contact" className="section contact"><div className="contactInfo"><span className="eyebrow">05 · Contact</span><h2>Discuss your<br/>next project.</h2><p>Send a concise project brief, drawings or scope requirements. Karam Engineering will review the inquiry and respond through direct email.</p><div className="details"><a href={`mailto:${site.email}`}>{site.email}</a><a href={`tel:${site.phone.replace(/\s/g,"")}`}>{site.phone}</a><span>{site.location}</span><a href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow/></a></div></div><ContactForm/></section>
</main><footer><div className="brand footerBrand"><span className="mark">RK</span><span>KARAM<br/><b>ENGINEERING</b></span></div><p>Structural Engineering · Quantity Surveying</p><p>© {new Date().getFullYear()} Karam Engineering</p></footer></>}
